Desktop version
vikas924/Portfolio-setup-and-mobilefirst pull request #5
Opened 2023-02-24 17:29 UTC by vikas924

Hello there,

In this project, I have set up a "Portfolio-setup-and-mobilefirst" repository. My tasks include:

1.Documented a professional README.md.
2.Included a .gitignore file in main branch.
3.Created a new branch according to the GitHub flow rules.
4.Added files in new branch with seperate commits.
5.Added html file that includes desktop version for portfolio mobile first website.
6.Added css file that include styles for desktop version.

2023-02-24 18:42 UTC, huseyinbiyik requested changes
Hi @francis450,

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
![Almost there](https://media.giphy.com/media/Rv6GGaNrRbtNConlYo/giphy.gif)

## Highlights
- Mobile first approach followed 📱 
- Linter set up well and checks pass 🟢
- Github flow followed 👌
- .gitignore used to ignore requested files 📁
- PR description is descriptive 📝

## Required Changes ♻️
- Kindly make sure your page doesn't get broken between the responsive sizes. Some sections respond very well to different screen sizes, some do not. You can use flex or grid to reach that. Please check the GIF below to understand what I mean.
![Screen Recording 2023-02-24 at 9 26 55 PM](https://user-images.githubusercontent.com/25887253/221261878-f88a8b10-c544-4ab6-8c34-e085220bb8d6.gif)

-  Please make sure your commit messages are meaningful and descriptive for your next commits. Use imperative tense and capitalize the first word. For example, 
👌"Add logo to navigation bar"
👌"Fix close button functionality on mobile navbar"
❌ "Added logo to navigation bar"
❌ "Added HTML"

_Check the comments under the review._




Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-24 18:42 UTC, huseyinbiyik commented on style.css
> +  .card {
Great job, you implemented the design very well. But there is a nuance you need to consider here. On the Figma template you will see a hand cursor. It means when you hover over the card, it should look like that. Kindly add hover state looks like your first card. Pleae remember to add See Project button to take the user to the project page. 👨‍🎨

<img width="788" alt="Screenshot 2023-02-24 at 8 57 32 PM" src="https://user-images.githubusercontent.com/25887253/221259613-2fad3d2c-99ec-4c4b-98ff-e6c0b82038b9.png">
<img width="1438" alt="Screenshot 2023-02-24 at 9 00 23 PM" src="https://user-images.githubusercontent.com/25887253/221259637-803ccc34-ff55-42b3-9ad8-b5d99f66b09c.png">

2023-02-24 18:42 UTC, huseyinbiyik commented on style.css
> +  .line {
Good job with adding the line as separator. But let's add space before it. Also I highly recommend you to use hr element instead of a and image element.  👍 
<img width="1438" alt="Screenshot 2023-02-24 at 9 07 40 PM" src="https://user-images.githubusercontent.com/25887253/221259844-0081f6b0-5ada-43b1-b500-1cdd92f8e81e.png">
<img width="749" alt="Screenshot 2023-02-24 at 9 09 38 PM" src="https://user-images.githubusercontent.com/25887253/221259855-1025091c-ac64-4e29-9cd6-c896c77c4cc4.png">

2023-02-24 18:42 UTC, huseyinbiyik commented on style.css
> +  .header {
Good job with implementing a responsive header. 👍   But let's make sure they are aligned well to the center like on the Figma template.
<img width="749" alt="Screenshot 2023-02-24 at 9 16 45 PM" src="https://user-images.githubusercontent.com/25887253/221259314-92b15280-cffa-4ba1-8dd5-0cbdf66958bf.png">
<img width="1440" alt="Screenshot 2023-02-24 at 9 17 02 PM" src="https://user-images.githubusercontent.com/25887253/221259324-c3845b0b-8884-4de0-b94f-6be8189eeb03.png">

2023-02-24 18:42 UTC, huseyinbiyik commented on index.html
> +        </nav>
Great job using a semantic nav element for the menu. But let's make sure we are using it correctly. The structure needs to look like the below.
```
<nav>
 <ul>
   <li><a href="#projects">Portfolio</a></li>
   <li><a href="#about">About</a></li>
...etc
  </ul>
</nav>
```

Also please take out the logo from the nav element. In this way, it will be more semantic. Check this [link](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/header) to learn more about semantic header.

2023-02-25 12:44 UTC, OyePriscilla requested changes
Hi @vikas924 👏, 

Great work on making the changes requested by a previous reviewer 👏 

You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

![so-close-so-close-seth-meyers](https://user-images.githubusercontent.com/103386183/196425724-8ca5825c-b02a-4983-b976-4bd0a2f70f9a.gif)

 ## Highlights
Linters passed ✔️ 
Use Grid and Flexbox to layout element on the page ✔️ 
Made some required changes ✔️ 


 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-25 12:44 UTC, OyePriscilla commented on style.css
> +  .header {
- [ ] As pointed out earlier, please kindly adjust the header items to align properly with the other contents on the page. I observed that the background image is not fully displayed contrary to your previous design, kindly work on this as well. Kindly note that implementing all these will show how well you pay attention to details. 👍 

## Your Design 
![Untitled](https://user-images.githubusercontent.com/103386183/221356665-d1ad470c-8d22-4b96-a4da-1f22b28dc511.jpg)

2023-02-25 12:44 UTC, OyePriscilla commented on style.css
> +  * {
- [ ] In the process of making the app responsive (@ exactly 768px) as suggested earlier, I observed some things that came up and we need to adjust:

1.  There is no space between the `nav` items.
2.  Multi-Post Stories text and button are overlapped.
3.  The Project cards text are overlapped with other content.
4.  The About Me background-image is overlapped with the text.

Kindly implement all these to give your app a great User Interface. 👍

2023-02-25 16:06 UTC, RaoAkif approved these changes
## STATUS: APPROVED 🎉🎉🎉

Hi @vikas924, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![approve-image](https://ci5.googleusercontent.com/proxy/zq80mRZVpq-eAhdzmvNYP-LJmESV4U2mCLkUDj-J77H6FKB6oLO-eL8kGFENlnk15aQQPnJ2K7hSGZiaZBHMKFZEM6yCAT5H0leJxszpiJ_ZRxNc5L9uv6Wf0BFZUomZYiYN6ppiHgltD6qjc_Kh8RbH3b4nVLPghJlpfxM29IAi_q8djloxFmcQQ_I2iIY_rYXVUeBiSfNsVRfk0iq3wo75_nf9QHejNs5EwcDwp7n4vukAV0rFF6xBnAenIBlJ9_CuSGN37pZ0FDROc_LU_rInohwgD5sTJnITUxeXsq5juhu5btEu0AhtqpFV5MDVTQMfZw=s0-d-e1-ft#https://camo.githubusercontent.com/b4e8f035e0f2d20302034402026b8df675e3a9dd93b722d1b0a047112e68044d/68747470733a2f2f632e74656e6f722e636f6d2f4a52665739444c534f764141414141432f7365616c2d7365616c2d6f662d617070726f76616c2e676966)

## Highlights
✔ Linters are on point 
✔ Splendid work with the README file
✔ Great use of GitHub flow
✔ Good code design and implementation

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-25 16:11 UTC, merged

2023-02-27 09:28 UTC, AlphaNtihinduka reviewed
Hi @vikas924 ,

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

# Invalid Code Review Request ❌ 

You have submitted a project with a different milestone. Kindly create a new pull request or issue with the live link available in either or both README file of that branch or the PR description

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready pray

Cheers and Happy coding!clapclapclap

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.